///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//import org.junit.Test;
//
//import de.wesim.imapnotes.IMAPBackend;
//
//import static org.junit.Assert.*;
//
//import java.util.List;
//
//import javax.mail.Message;
//import javax.mail.MessagingException;
//
//import org.junit.Ignore;
//
//public class AppTest {
//	
//	@Ignore
//    @Test 
//    public void testAppHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//    }
//	
//	@Test 
//    public void exungeTest() throws MessagingException {
//	 IMAPBackend backend = IMAPBackend.initNotesFolder("Notes/Playground");
////   backend.getMessages()
////	backend.createNewMessage("Hello World!", "This is THE house of Santa Clause.");
//   
//   //final Session session = backend.getSession();
//   //this.backend.initNotesFolder("Notes");
//
//   List<Message> messages = backend.getMessages();
//   System.out.println("Anzahl der NAchrichten:" + messages.size());
//   backend.cleanup();
//   System.out.println("Anzahl der NAchrichten:" + messages.size());
//    }
//	
//	 @Test 
//	    public void deleteAllTest() throws MessagingException {
//		 IMAPBackend backend = IMAPBackend.initNotesFolder("Notes/Playground");
////       backend.getMessages()
////		backend.createNewMessage("Hello World!", "This is THE house of Santa Clause.");
//       
//       //final Session session = backend.getSession();
//       //this.backend.initNotesFolder("Notes");
//
//       List<Message> messages = backend.getMessages();
//       System.out.println("Anzahl der NAchrichten:" + messages.size());
//       for (Message msg : messages) {
//    	  backend.deleteMessage(msg);
//        //  break;
//       }
////       Message msg = backend.getMessageByUID(7);
////       backend.dumpMessage(msg);
//       messages = backend.getMessages();
//       System.out.println("Anzahl der NAchrichten:" + messages.size());
//	    }
//}
